# Docker Composeのバージョンを指定
version: '3.8'

# 起動するサービス（コンテナ）を定義
services:
  # 'web'という名前のサービスを定義
  web:
    # ビルドに関する設定
    build:
      # Dockerfileがあるコンテキスト（場所）を指定
      # '.' は、このdocker-compose.ymlファイルと同じディレクトリを指します。
      context: .
      # 使用するDockerfileの名前を指定
      dockerfile: Dockerfile
    # ポートのマッピング設定
    ports:
      # ローカルPCの5000番ポートを、コンテナの5000番ポートに接続します。
      - "5000:5000"
    # ボリュームのマッピング設定
    volumes:
      # ローカルの現在のディレクトリを、コンテナの/appディレクトリにマウントします。
      # これにより、ローカルでコードを修正すると、コンテナを再ビルドしなくても即座に反映されます。
      - .:/app
    # 環境変数の設定
    env_file:
      # .envファイルから環境変数を読み込み、コンテナ内で使えるようにします。
      - .env
